# Site settings
name: William Tong
title: William Tong
description: Just a dude who loves solving problems and creating stuff with code.
url: "http://willtong.com"
baseurl: ""
email: wmtong@wustl.edu
social:
  - title: email
    url: mailto:wmtong@wustl.edu
  - title: github
    url: https://github.com/wmtong
  - title: linkedin
    url: https://www.linkedin.com/in/wmtong

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
